baseurl = "/"
title = "fml blog"
theme = "onetwothree"
publishDir = "docs/"
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "wrathematics"

[params]
    navigation = ["about.md"]
    style = "3"
    twitter = "wrathematics"

[permalinks]
    post = "/:year/:month/:day/:slug/"
